[[plugins]]
  package = "@netlify/plugin-nextjs"

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  # Add your environment variables here for the build process
  WORDPRESS_URL = "https://futalis24.de"
  WORDPRESS_HOSTNAME = "futalis24.de"
  WORDPRESS_WEBHOOK_SECRET = "your-secret-key-here"

[[redirects]]
  from = "/admin"
  to = "https://futalis24.de/wp-admin"
  status = 301
  force = true